version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: worktime-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/usr/share/nginx/html:ro
    networks:
      - worktime-network
    restart: unless-stopped
    depends_on:
      - server

networks:
  worktime-network:
    driver: bridge
