

services:
  postgres:
    image: postgres:15-alpine
    container_name: worktime-postgres
    environment:
      POSTGRES_DB: worktime_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/database/migrations.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - worktime-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: worktime-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@worktime.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - worktime-network
    restart: unless-stopped

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: worktime-server
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: worktime_tracker
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-development-jwt-secret-key-here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server/src:/app/src
      - ./server/logs:/app/logs
    networks:
      - worktime-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  worktime-network:
    driver: bridge 