# docker-compose.prod.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wt-db
    environment:
      POSTGRES_DB: worktime_tracker
      POSTGRES_USER: worktime_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wt-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wt-server
    environment:
      - DB_HOST=db
      - JWT_SECRET=your_super_secure_jwt_secret_minimum_32_characters
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - wt-network

volumes:
  db_data:

networks:
  wt-network:
