version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: worktime-postgres
    environment:
      POSTGRES_DB: worktime_tracker_prod
      POSTGRES_USER: worktime_user
      POSTGRES_PASSWORD: SuperSecurePassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/database/migrations.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - worktime-network
    restart: unless-stopped

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: worktime-server
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: worktime_tracker_prod
      DB_USER: worktime_user
      DB_PASSWORD: SuperSecurePassword123
      PORT: 3001
      DB_SSL: "false"
      JWT_ACCESS_SECRET: SecureJWTAccessSecret12345678901234567890
      JWT_REFRESH_SECRET: SecureJWTRefreshSecret12345678901234567890
      CORS_ORIGINS: https://localhost
    volumes:
      - ./server/logs:/app/logs
      - ./server/uploads:/app/uploads
    ports:
      - "3001:3001"
    networks:
      - worktime-network
    restart: unless-stopped
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: worktime-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - worktime-network
    restart: unless-stopped
    depends_on:
      - server

volumes:
  postgres_data:

networks:
  worktime-network:
    driver: bridge 